<?php
return [
    'SUPABASE_URL' => 'https://example.supabase.co',
    'SUPABASE_ANON_KEY' => 'public-anon-key',
    'TURNSTILE_SITE_KEY' => null,
    'RECAPTCHA_SITE_KEY' => null,
    'RECAPTCHA_SECRET_KEY' => null,
    'CONTACT_RECIPIENT' => null,
    'ADMIN_EMAIL' => null,
    'PUBLIC_BASE_URL' => 'https://accessibleaudio.co.za',
    'EMAIL_SMTP_HOST' => null,
    'EMAIL_SMTP_PORT' => 465,
    'EMAIL_ADDRESS' => null,
    'EMAIL_PASSWORD' => null,
    'MAX_UPLOAD_BYTES' => 10485760,
    'PAYFAST_MERCHANT_ID' => null,
    'PAYFAST_MERCHANT_KEY' => null,
    'PAYFAST_PASSPHRASE' => null,
    'PAYFAST_SANDBOX' => true,
    // Only for PayFast's public 10000100 sandbox account, which currently rejects signed test forms.
    'PAYFAST_UNSIGNED_SANDBOX' => false,
    'OPENROUTER_API_KEY' => null,
    'OPENROUTER_TTS_MODEL' => 'google/gemini-3.1-flash-tts-preview',
    'LAME_BINARY' => __DIR__ . '/bin/lame',
    'TTS_CHUNK_CHARACTERS' => 4500,
    'TTS_REQUEST_TIMEOUT' => 300,
    'WORKER_CHUNKS_PER_RUN' => 1,
];
